[pytest]

testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --strict-markers
    --tb=short
    --timeout=300
    --timeout-method=thread

markers =
    smoke: Smoke test cases
    sanity: Sanity test cases
    regression: Regression test cases